# Monitor process executions from OpenClaw (rate limited)
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: openclaw-process-exec
spec:
  kprobes:
    - call: "sys_execve"
      syscall: true
      args:
        - index: 0
          type: "string"
      selectors:
        - matchBinaries:
            - operator: "In"
              values:
                - "/usr/bin/node"
                - "/usr/local/bin/node"
          matchActions:
            - action: Post
