# Detect access to sensitive files (rate limited)
apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: openclaw-sensitive-files
spec:
  kprobes:
    - call: "security_file_open"
      syscall: false
      args:
        - index: 0
          type: "file"
      selectors:
        - matchBinaries:
            - operator: "In"
              values:
                - "/usr/bin/node"
                - "/usr/local/bin/node"
          matchArgs:
            - index: 0
              operator: "Prefix"
              values:
                - "/etc/shadow"
                - "/etc/sudoers"
                - "/root/.ssh/"
                - ".ssh/id_"
                - ".ssh/authorized_keys"
                - ".aws/credentials"
                - ".kube/config"
                - ".config/gcloud/"
                - ".openclaw/credentials/"
          matchActions:
            - action: Post
